
server:
  port: 8080
  servlet:
    context-path: /sogno-di-ale-server
  tomcat:
    relaxed-query-chars:
      - "{"
      - "["
      - "|"
      - "]"
      - "}"
    relaxed-path-chars:
      - "{"
      - "["
      - "|"
      - "]"
      - "}"
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      condition-unless: discardlogs
      pattern: '[%{yyyy-MM-dd HH:mm:ss:SSS}t - tomcat10-ACCESSLOG] > [%h,%{x-forwarded-for}i] - "%r" %s %b %{ms}T'

params:
  env: "DEV"
  fileStorage: "C:/Users/consonni/git/data/"

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      cors:
        allowed-origins: "*"
        allowed-origins-patterns: "*"
        allowed-headers: "*"
        allowed-methods: "*"
        exposed-headers: "Authorization, Cache-Control, Content-Type"

logging:
  level:
    liquibase: ERROR
    org:
      hibernate:
        SQL: INFO
      springframework:
        web:
          client:
            RestTemplate: DEBUG
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : [%X{Slf4jMDCFilter.UUID}] : %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : [%X{Slf4jMDCFilter.UUID}] : %m%n%wEx"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
  packagesToScan: "it.ale.controller"

spring:
  profiles:
    active: dev
  liquibase:
    enabled: false
    change-log: classpath:./config/liquibase/db.changelog-init.xml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sognoDiAle
    username: user
    password: password
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: sognoDiAle

paypal:
  client:
    id: clientId
    secret: secret
  mode: mode